#!/bin/bash

RESET=""
WAYLAND_VIDEO="false"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

while [ 1 ]
do
	    GDK_BACKEND=x11 ./obplayer_check $@ $RESET 

        if [ $? -eq 37 ]
        then
            echo "deleting data.db and restarting with -r"
            #rm ~/.openbroadcaster/data.db
            RESET="-r"
        else
            RESET=""
        fi

        if [ $WAYLAND_VIDEO == "true" ]; then
            echo "Wayland not supported! Playing now running under X11 mode."
            GDK_BACKEND=x11
        fi

	sleep 4
done
